// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/landing": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/paypal-success": {
    params: {};
  };
  "/results": {
    params: {};
  };
  "/rules": {
    params: {};
  };
  "/task": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/admin" | "/landing" | "/login" | "/paypal-success" | "/results" | "/rules" | "/task" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./admin/page.jsx": {
    id: "admin/page";
    page: "/admin";
  };
  "./landing/page.jsx": {
    id: "landing/page";
    page: "/landing";
  };
  "./login/page.jsx": {
    id: "login/page";
    page: "/login";
  };
  "./paypal-success/page.jsx": {
    id: "paypal-success/page";
    page: "/paypal-success";
  };
  "./results/page.jsx": {
    id: "results/page";
    page: "/results";
  };
  "./rules/page.jsx": {
    id: "rules/page";
    page: "/rules";
  };
  "./task/page.jsx": {
    id: "task/page";
    page: "/task";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "admin/page": typeof import("./src/app/./admin/page.jsx");
  "landing/page": typeof import("./src/app/./landing/page.jsx");
  "login/page": typeof import("./src/app/./login/page.jsx");
  "paypal-success/page": typeof import("./src/app/./paypal-success/page.jsx");
  "results/page": typeof import("./src/app/./results/page.jsx");
  "rules/page": typeof import("./src/app/./rules/page.jsx");
  "task/page": typeof import("./src/app/./task/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};